# Generated by Django 4.2.16 on 2024-11-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyprofile',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyprofile',
            name='access_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='spotifyprofile',
            name='refresh_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='spotifyprofile',
            name='spotify_id',
            field=models.CharField(max_length=255),
        ),
    ]
