# Generated by Django 4.2.16 on 2024-11-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0002_spotifyprofile_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifyprofile',
            name='expires_at',
        ),
        migrations.AlterField(
            model_name='spotifyprofile',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='spotifyprofile',
            name='refresh_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='spotifyprofile',
            name='spotify_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
