# Generated by Django 4.2.16 on 2024-11-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0003_remove_spotifyprofile_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyprofile',
            name='expires_at',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
